# Generated by Django 5.1.5 on 2025-02-04 15:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RasterData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "raster",
                    django.contrib.gis.db.models.fields.RasterField(
                        help_text="Data raster GeoTIFF yang disimpan dalam PostGIS",
                        srid=4326,
                    ),
                ),
            ],
        ),
    ]
