# Generated by Django 5.1.6 on 2025-08-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aod_data', '0011_alter_polygondatapm25_pm25id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sattellite',
            new_name='Satellite'
        ),
        migrations.RenameModel(
            old_name='RasterData',
            new_name='AerosolOpticalDepth'
        ),
        migrations.RenameModel(
            old_name='PolygonData',
            new_name='AerosolOpticalDepthPolygon'
        )
    ]
