# Generated by Django 5.1.6 on 2025-08-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aod_data', '0012_auto_20250801_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aerosolopticaldepth',
            old_name='time_retrieve',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='aerosolopticaldepth',
            old_name='sattellite',
            new_name='satellite',
        ),
        migrations.RenameField(
            model_name='pm25dataestimate',
            old_name='time',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='satellite',
            old_name='sattelite_name',
            new_name='satellite_name',
        ),
    ]
